# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "prepare"
  - "infra"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "codefresh-contrib/aws-workshop-demos"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github-1"
    stage: "prepare"

  PlanWithTerraform:
    image: hashicorp/terraform:1.3.7
    title: "Planning Lambda method"
    working_directory: "${{clone}}" 
    stage: infra
    commands:
      - cp -r /codefresh/volume/sensitive/.kube/ ~/.kube 
      - cd lambda
      - terraform init
      - terraform plan



